Api/Controllers/poamUpload.controller.js
=> Revert commit for further testing and review

Front End/poam-app/src/app/pages/poam-processing/poam-details/poam-details.component.html, Front End/poam-app/src/app/pages/poam-processing/poam-details/poam-details.component.ts, Front End/poam-app/src/index.html
-Fixed a bug that would cause the application to remain stuck on "Loading..." when refreshed into index.html.
-Modified data structures of data items within the POAM smart table to allow for placeholder(default value)
=> Bug fixes and general improvements

Api/Services/mysql/permissionsService.js, Api/specification/poam-manager.yaml, Front End/poam-app/src/app/app-routing.module.ts, Front End/poam-app/src/app/app.module.ts, Front End/poam-app/src/app/auth.guard.ts, Front End/poam-app/src/app/pages/asset-processing/asset/asset.component.ts, Front End/poam-app/src/app/pages/collection-processing/collection/collection.component.ts, Front End/poam-app/src/app/pages/label-processing/label/label.component.html, Front End/poam-app/src/app/pages/poam-processing/poam-details/poam-details.component.ts, Front End/poam-app/src/app/pages/user-processing/user/user.component.ts
-Modified data structures of  items within all remaining smart tables to allow for placeholder(default value) and proper selection.
-Fixed a bug that would prevent updating user permissions when a collection is changed simultaneously.
-Small adjustment to UI of label-processing
=> General improvements and bug fixes

Api/Models/poam.model.js, Api/Services/mysql/poamService.js, Api/specification/poam-manager.yaml, Database/POAM_Tracking_Tool_Data_Model.sql, Front End/poam-app/src/app/Shared/utils/excel-data.service.ts, Front End/poam-app/src/app/app.module.ts, Front End/poam-app/src/app/pages/asset-processing/asset/asset.component.ts, Front End/poam-app/src/app/pages/collection-processing/collection/collection.component.ts, Front End/poam-app/src/app/pages/poam-processing/poam-details/poam-details.component.html, Front End/poam-app/src/app/pages/poam-processing/poam-details/poam-details.component.ts, Front End/poam-app/src/app/pages/poam-processing/poams.module.ts, Front End/poam-app/src/app/pages/user-processing/user/user.component.ts
-Added "Extension Time Allowed" to the POAM Details component. Drop-down options include, 0, 30, 60, 90, 180, and 365 days. The value dynamically updates to 30 days with the selection of raw severity; Cat I - Critical/High = 30 days, CAT II - Medium = 180 days, CAT III - Low = 365 days. *The extension time allowed can still be modified by a user after it is dynamically set.
-Removed "Actions" text from angular2-smart-table
-Swapped datepicker inside of POAM creation to Nebular datepicker.
-Added logic to prefill the submitted date of a new POAM with the current date.
-Created database stored procedure and event to run every night, at midnight, and update POAM status to Expired if the scheduled completion date + the allowed extension time < current date.
=> General updates. Reference pull request for full details.

Api/Services/mysql/assetLabelService.js, Api/Services/mysql/assetService.js, Api/Services/mysql/authService.js, Api/Services/mysql/collectionApproverService.js, Api/Services/mysql/collectionService.js, Api/Services/mysql/permissionsService.js, Api/Services/mysql/poamApproverService.js, Api/Services/mysql/poamAssetService.js, Api/Services/mysql/poamAssigneeService.js, Api/Services/mysql/poamLabelService.js, Api/Services/mysql/poamMilestoneService.js, Api/Services/mysql/poamService.js, Api/Services/mysql/usersService.js, Api/Services/mysql/utils.js
Updated all SQL statements to parameterized queries.
=> Reference pull request for full details.

.github/workflows/sonarcloud.yml
=> Sonarcloud config update

api/.env
THIS ENV FILE IS PROVIDED AS AN EXAMPLE.  PLEASE CHANGE THE VALUES TO MATCH YOUR ENVIRONMENT.
=> Add sample .env

.github/workflows/release.yml
=> Revert "Include admin PAT envvar for rule conflict"

.github/workflows/release.yml
=> Revert "Update 'Release New Version' action"

api/package-lock.json, api/package.json, client/package-lock.json, client/package.json, client/src/app/pages/admin-processing/app-info/app-info.component.html, client/src/app/pages/admin-processing/asset-delta/asset-delta.component.html, client/src/app/pages/admin-processing/nessus-plugin-mapping/nessus-plugin-mapping.component.html, client/src/app/pages/import-processing/stigmanager-import/stigManagerAssetsTable/stigManagerAssetsTable.component.html, client/src/app/pages/import-processing/stigmanager-import/stigManagerPoamAssetsTable/stigManagerPoamAssetsTable.component.html, client/src/app/pages/import-processing/stigmanager-import/stigManagerReviewsTable/stigManagerReviewsTable.component.html, client/src/app/pages/import-processing/stigmanager-import/stigmanager-import.component.html, client/src/app/pages/import-processing/tenable-import/components/tenableAssetsTable/tenableAssetsTable.component.html, client/src/app/pages/import-processing/tenable-import/components/tenableHostAssetsTable/tenableHostAssetsTable.component.html, client/src/app/pages/import-processing/tenable-import/components/tenableSelectedVulnerabilities/tenableSelectedVulnerabilities.component.html, client/src/app/pages/import-processing/tenable-import/components/tenableVulnerabilities/tenableVulnerabilities.component.html, client/src/app/pages/poam-processing/poam-details/components/poam-approvers/poam-approvers.component.html, client/src/app/pages/poam-processing/poam-details/components/poam-assets/poam-assets.component.html, client/src/app/pages/poam-processing/poam-details/components/poam-associated-vulnerabilities/poam-associated-vulnerabilities.component.html, client/src/app/pages/poam-processing/poam-details/components/poam-labels/poam-labels.component.html, client/src/app/pages/poam-processing/poam-details/components/poam-milestones/poam-milestones.component.html, client/src/app/pages/poam-processing/poam-details/components/poam-teams/poam-teams.component.html
fix: col scope standardization
=> fix: col scope standardization

client/src/app/pages/poam-processing/poam-details/poam-details.component.ts
fix: "I am async, I must await" - confirmSubmit(), probably
=> fix: "I am async, I must await" - confirmSubmit(), probably

api/Models/iav.model.js, api/Services/importService.js, api/Services/migrations/0012.js
fix: support VRAM changes to column value standard
=> fix: support VRAM changes to column value standard

client/src/app/layout/components/app.layout.component.ts, client/src/app/pages/poam-processing/poam-details/components/poam-milestones/poam-milestones.component.spec.ts, client/src/app/pages/poam-processing/poam-details/components/poam-milestones/poam-milestones.component.ts
chore: update poam milestones testing with mock signal
=> chore: update poam milestones testing with mock signal

client/src/app/pages/import-processing/tenable-import/components/solutions/tenableSolutions.component.html, client/src/app/pages/import-processing/tenable-import/components/solutions/tenableSolutions.component.ts, client/src/app/pages/import-processing/tenable-import/components/tenableSelectedVulnerabilities/tenableSelectedVulnerabilities.component.html, client/src/app/pages/import-processing/tenable-import/components/tenableSelectedVulnerabilities/tenableSelectedVulnerabilities.component.ts
style: Add table loading animation(s)
=> style: Add table loading animation(s)

client/src/app/pages/import-processing/tenable-import/components/tenableSelectedVulnerabilities/tenableSelectedVulnerabilities.component.scss, client/src/app/pages/poam-processing/poam-details/poam-details.component.scss
style: PrimeNG v20 styling tweaks
=> style: PrimeNG v20 styling tweaks

client/src/app/pages/admin-processing/collection-processing/collection-processing.component.ts
fix: can not view collections on initial CPAT setup
=> fix: can not view collections on initial CPAT setup

client/src/app/pages/admin-processing/aaPackage-processing/aaPackage-processing.component.html, client/src/app/pages/admin-processing/app-configuration/app-configuration.component.html, client/src/app/pages/admin-processing/asset-delta/asset-delta.component.html, client/src/app/pages/admin-processing/assignedTeam-processing/assignedTeam-processing.component.html, client/src/app/pages/admin-processing/collection-processing/collection-processing.component.html, client/src/app/pages/admin-processing/user-processing/user-processing.component.html, client/src/app/pages/admin-processing/user-processing/user/user.component.html, client/src/app/pages/import-processing/stigmanager-import/stigManagerAssetsTable/stigManagerAssetsTable.component.html, client/src/app/pages/import-processing/stigmanager-import/stigManagerPoamAssetsTable/stigManagerPoamAssetsTable.component.html, client/src/app/pages/import-processing/stigmanager-import/stigManagerReviewsTable/stigManagerReviewsTable.component.html, client/src/app/pages/import-processing/stigmanager-import/stigmanager-import.component.html, client/src/app/pages/import-processing/tenable-import/components/tenableAssetsTable/tenableAssetsTable.component.html, client/src/app/pages/import-processing/tenable-import/components/tenableHostAssetsTable/tenableHostAssetsTable.component.html, client/src/app/pages/import-processing/tenable-import/components/tenableSelectedVulnerabilities/tenableSelectedVulnerabilities.component.html, client/src/app/pages/import-processing/tenable-import/components/tenableVulnerabilities/tenableVulnerabilities.component.html, client/src/app/pages/poam-processing/poam-grid/poam-grid.component.html
fix: missing id or name attributes
=> fix: missing id or name attributes

api/utils/config.js
perf: increase default rate limiter to 10000/15min
=> perf: increase default rate limiter to 10000/15min

api/bootstrap/middlewares.js
perf: refactor tenable request proxying
=> perf: refactor tenable request proxying

api/Controllers/Asset.js, api/Services/assetService.js
chore: assetService error handling and db table reference standardization
=> chore: assetService error handling and db table reference standardization

api/bootstrap/client.js, api/utils/config.js, client/src/app/app.component.html, client/src/app/app.component.ts, client/src/app/common/components/inactivity-warning/inactivity-warning.component.ts, client/src/app/core/auth/services/inactivity.service.ts, client/src/app/layout/components/app.layout.component.ts, docs/source/install/envvars.csv
feat: automatically log out after a period of inactivity
This setting can be customized by specifying, in minutes, `CPAT_INACTIVITY_TIMEOUT`
=> feat: automatically log out after a period of inactivity

client/src/app/pages/poam-processing/poam-details/poam-details.component.ts
feat: Always allow CAT-I Approvers to modify SCD
=> feat: Always allow CAT-I Approvers to modify SCD

client/src/app/pages/poam-processing/poam-assigned-grid/poam-assigned-grid.component.ts, client/src/app/pages/poam-processing/poam-grid/poam-grid.component.html, client/src/app/pages/poam-processing/poam-grid/poam-grid.component.ts
fix: POAM grid assigned team filter
=> fix: POAM grid assigned team filter

api/.prettierrc, api/bootstrap/client.js, api/utils/config.js, client/src/app/common/services/setPayload.service.ts, client/src/app/core/auth/services/inactivity.service.ts, docs/source/install/envvars.csv
feat: ASD STIG Auto logoffs
- Update to add separate admin logoff with 10 minute default
=> feat: ASD STIG Auto logoffs

client/src/app/pages/import-processing/tenable-import/components/tenableVulnerabilities/tenableVulnerabilities.component.ts, client/src/app/pages/import-processing/tenable-import/tenable.component.html, client/src/app/pages/import-processing/tenable-import/tenable.component.ts
feat: Add Vulnerabilities Published 30+ day to the tabbed Tenable view
=> feat: Add Vulnerabilities Published 30+ day to the tabbed Tenable view

client/src/app/pages/poam-processing/poam-details/poam-details.component.html, client/src/app/pages/poam-processing/poam-details/poam-details.component.ts
feat: Remove Global Mitigation Tab if GM is not toggled
=> feat: Remove Global Mitigation Tab if GM is not toggled

client/src/app/pages/poam-processing/poam-manage/poam-manage.component.html, client/src/app/pages/poam-processing/poam-manage/poam-manage.component.scss, client/src/app/pages/poam-processing/poam-manage/poam-manage.component.ts
feat: expand assigned POAM grid to full page width
=> feat: expand assigned POAM grid to full page width

client/src/app/common/utils/poam-export-status-selection.component.ts, client/src/app/common/utils/poam-export.service.ts, client/src/app/pages/poam-processing/poam-grid/poam-grid.component.ts
feat: Prompt to select POAM statuses prior to exporting
=> feat: Prompt to select POAM statuses prior to exporting

client/src/app/pages/poam-processing/poam-grid/poam-grid.component.ts
fix: handle promise rejections in Excel file generation
=> fix: handle promise rejections in Excel file generation

client/src/app/pages/poam-processing/poam-assigned-grid/poam-assigned-grid.component.html, client/src/app/pages/poam-processing/poam-assigned-grid/poam-assigned-grid.component.ts
feat: Assigned grid, sort by POAM status groups
=> feat: Assigned grid, sort by POAM status groups

client/src/app/common/utils/poam-export.service.ts, client/src/app/pages/poam-processing/poam-grid/poam-grid.component.ts
feat: Include associated vulnerabilities in POAM export
=> feat: Include associated vulnerabilities in POAM export

client/src/app/pages/poam-processing/poam-details/components/poam-associated-vulnerabilities/poam-associated-vulnerabilities.component.spec.ts, client/src/app/pages/poam-processing/poam-grid/poam-grid.component.spec.ts
chore: testing addition and updates
=> chore: testing addition and updates

client/src/app/pages/import-processing/stigmanager-import/stigManagerPoamAssetsTable/stigManagerPoamAssetsTable.component.html, client/src/app/pages/import-processing/stigmanager-import/stigManagerPoamAssetsTable/stigManagerPoamAssetsTable.component.ts, client/src/app/pages/import-processing/tenable-import/components/tenableAssetsTable/tenableAssetsTable.component.html, client/src/app/pages/import-processing/tenable-import/components/tenableAssetsTable/tenableAssetsTable.component.ts
feat: POAM asset table, update team column to display team name
=> feat: POAM asset table, update team column to display team name

client/src/app/pages/admin-processing/assignedTeam-processing/assignedTeam-processing.component.ts
fix: save team permissions during new team creation
=> fix: save team permissions during new team creation

client/src/app/pages/admin-processing/user-processing/user-processing.component.ts, client/src/app/pages/admin-processing/user-processing/user/user.component.html, client/src/app/pages/admin-processing/user-processing/user/user.component.ts
feat: Add 'Last Access' to User Management table
=> feat: Add 'Last Access' to User Management table

api/Services/poamExtensionService.js
fix: Update POAM extension update response
=> fix: Update POAM extension update response

client/src/app/pages/poam-processing/poam-assigned-grid/poam-assigned-grid.component.html, client/src/app/pages/poam-processing/poam-assigned-grid/poam-assigned-grid.component.ts
feat: add associated vulns to Assigned POAM table and add associated vulns to searchable parameters of the POAM assigned grid.
=> feat: add associated vulns to Assigned POAM table

client/src/app/pages/poam-processing/poam-assigned-grid/poam-assigned-grid.component.html, client/src/app/pages/poam-processing/poam-assigned-grid/poam-assigned-grid.component.ts, client/src/app/pages/poam-processing/poam-manage/poam-manage.component.html, client/src/app/pages/poam-processing/poam-manage/poam-manage.component.scss
feat: add exporting functionality to assigned poam table
=> feat: add exporting functionality to assigned poam table

client/src/app/pages/admin-processing/user-processing/user/user.component.html
feat: Add dropdown toggle to Office/Org autocomplete
=> feat: Add dropdown toggle to Office/Org autocomplete

client/src/app/pages/import-processing/stigmanager-import/stigManagerAssetsTable/stigManagerAssetsTable.component.ts, client/src/app/pages/import-processing/stigmanager-import/stigManagerReviewsTable/stigManagerReviewsTable.component.scss, client/src/app/pages/import-processing/stigmanager-import/stigmanager-import.component.scss, client/src/app/pages/poam-processing/poam-details/poam-details.component.scss, client/src/app/pages/poam-processing/poam-details/poam-details.component.ts, client/src/app/pages/poam-processing/poam-grid/poam-grid.component.scss
chore: Fix formatting and update var names
=> chore: Fix formatting and update var names

client/src/app/pages/import-processing/tenable-import/components/tenableVulnerabilities/tenableVulnerabilities.component.ts
fix: Include Tenable tool in filter history
=> fix: Include Tenable tool in filter history

client/src/app/pages/import-processing/tenable-import/components/tenableVulnerabilities/tenableVulnerabilities.component.ts
fix: Tenable notContains operator
=> fix: Tenable notContains operator

client/src/app/common/utils/csv-export.service.ts, client/src/app/pages/import-processing/stigmanager-import/stigManagerReviewsTable/stigManagerReviewsTable.component.ts, client/src/app/pages/poam-processing/poam-assigned-grid/poam-assigned-grid.component.ts
=> perf: CSV export service

client/src/app/pages/admin-processing/user-processing/user-processing.component.html, client/src/app/pages/admin-processing/user-processing/user-processing.component.ts
=> feat: user table exporting
